### ISSUE TITLE
Typos in 1971.yml and 1991.yml

### ISSUE THREAD

**Issue by neilmpatterson** [jefmsmit/gdshowsdb#104]
Line 1363 of the 1971.yml and Line 5180 in 1991.yml had an indentation error causing yml parsing error in my environment. On windows 10, using WSL ubuntu, ruby '2.7.0' and rails 5.2.3 and sqlite3

Also had errors in 1971 for the songs named "Me And Bobby McGee" because the SongRef has it stored as "Me And Bobby Mcgee". 

I have never worked on a gem before so Im not quite sure exactly how to do this. But I think I can make changes to the yml and make a PR for that. If this is not appropriate or there is already an open issue for this, please let me know the proper way to do this.

**Comment by neilmpatterson** [comment]
Have a branch ready to push if you like @jefmsmit - I assume I need some kine of permission to push a branch up though. lmk

**Comment by jefmsmit** [comment]
@neilmpatterson you will have to create the branch under your fork, then open a PR please. Thanks for the contribution.

**Comment by alkenes** [comment]
I think that PR #105 closed this issue.

**Comment by jefmsmit** [comment]
@alkenes, I think you are correct. I will close.
