### ISSUE TITLE
1991/12/30 - Missing Dear Prudence Jam after Saint

### ISSUE THREAD

**Issue by jefmsmit** [jefmsmit/gdshowsdb#39]

**Comment by jacobcharleskillian** [comment]
Not finding this on other setlist databases.  Will listen to the show after last night's PITS and listen for Dear Prudence Jam.  I have a data modeling project in mind, and this dataset seems the most accessible.  I'd love to help clean it up.  My goal is to compare setlist variance between the GD and D&C for a blog I'm writing.  I like the simple YAML format.

**Comment by jacobcharleskillian** [comment]
So, some versions of this show on the archive have "Dear Prudence Jam" as a separate track.  It's not in the song_refs.yaml.  I can add it to song_refs.yaml and add it to the 1991.yaml (for 12/30) and I think I found another show with "hints of Dear Prudence" in a jam from 1992.  What version of UUIDs are you using for songs?  Version 4?  Any reason why I couldn't use https://www.uuidgenerator.net/ to create one?
