### ISSUE TITLE
1971 Missing Setlists

### ISSUE THREAD

**Issue by jacobcharleskillian** [jefmsmit/gdshowsdb#54]
Creating an omnibus issue for all 54 missing setlists from 1971.

Dates:

1971/01/21
1971/01/22
1971/02/19
1971/02/21
1971/02/24
1971/03/03
1971/03/05
1971/03/13
1971/03/14
1971/03/17
1971/03/18
1971/03/21
1971/03/24
1971/04/04
1971/04/05
1971/04/06
1971/04/07
1971/04/13
1971/04/14
1971/04/15
1971/04/17
1971/04/18
1971/04/21
1971/04/22
1971/04/25
1971/04/26
1971/04/27
1971/04/28
1971/05/29
1971/06/21
1971/07/02
1971/08/04
1971/08/05
1971/08/07
1971/08/14
1971/08/15
1971/08/24
1971/08/26
1971/10/19
1971/10/21
1971/10/22
1971/10/23
1971/10/24
1971/10/26
1971/10/27
1971/10/30
1971/11/06 - see issue #44 
1971/11/07 - see issue #36 
1971/11/11 - see issue #46 
1971/11/12 - see issue #48 
1971/11/14 - see issue #50 
1971/11/15 - see issue #52 
1971/11/17
1971/12/06

**Comment by jacobcharleskillian** [comment]
Will work on resolving the remaining missing setlists from 1971 and submit one commit for all of them going forward.

**Comment by jefmsmit** [comment]
Happy to have this issue to keep track, but I think I prefer a sub-issue and single PR per missing setlist. Its hard for me to grok otherwise.

**Comment by jacobcharleskillian** [comment]
Not familiar with grok.  Thanks for the new vocabulary!  I grok the need to
read more Heinlein now.  :)

I'll create a sub-issue per missing setlist.

**Comment by jefmsmit** [comment]
Amazing to see what poor shape 1971 is in. I'm guessing 65-71 are generally pretty bad. After we get through this issue we should cut a new release.
