### ISSUE TITLE
Add show info for 4/13/1969

### ISSUE THREAD

**Issue by jefmsmit** [jefmsmit/gdshowsdb#6]
No set list available. Recordings on archive.org.

**Comment by robertmazzo** [comment]
Hi,
Could the yaml files be used to import into a Sql Server DB ? I'm looking to cut my teeth using Angular 2 with MS Web Api and Sql Server, and writing a Dead Show website for fun.
Happy birthday Jerry !
Peace,
Bob Mazzo

**Comment by jefmsmit** [comment]
Can you please create a new issue for this?

**Comment by jefmsmit** [comment]
Fixed in 1.0.1
